//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using Xceed.wpf.Toolkit;

[assembly: EdmSchemaAttribute()]
#region Metadados de Relação EDM

[assembly: EdmRelationshipAttribute("imobiliariaModel1", "FK_cliente_imovel", "cliente", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(imobiliaria.cliente), "imoveis", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(imobiliaria.imoveis), true)]

#endregion

namespace imobiliaria
    
    {
    #region Contextos
    
    /// <summary>
    /// Nenhuma Documentação de Metadados disponível.
    /// </summary>
    public partial class imobiliariaEntities1 : ObjectContext
    {
        #region Construtores
    
        /// <summary>
        /// Inicializa um novo objeto imobiliariaEntities1 usando a cadeia de conexão localizada na seção 'imobiliariaEntities1' do arquivo de configuração do aplicativo.
        /// </summary>
        public imobiliariaEntities1() : base("name=imobiliariaEntities1", "imobiliariaEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicialize um novo objeto imobiliariaEntities1.
        /// </summary>
        public imobiliariaEntities1(string connectionString) : base(connectionString, "imobiliariaEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicialize um novo objeto imobiliariaEntities1.
        /// </summary>
        public imobiliariaEntities1(EntityConnection connection) : base(connection, "imobiliariaEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos Parciais
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriedades de ObjectSet
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        public ObjectSet<cliente> cliente
        {
            get
            {
                if ((_cliente == null))
                {
                    _cliente = base.CreateObjectSet<cliente>("cliente");
                }
                return _cliente;
            }
        }
        private ObjectSet<cliente> _cliente;
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        public ObjectSet<imoveis> imoveis
        {
            get
            {
                if ((_imoveis == null))
                {
                    _imoveis = base.CreateObjectSet<imoveis>("imoveis");
                }
                return _imoveis;
            }
        }
        private ObjectSet<imoveis> _imoveis;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método preterido para adicionar um novo objeto ao EntitySet cliente. Em vez disso, experimente usar o método .Add da propriedade ObjectSet&lt;T&gt; associada.
        /// </summary>
        public void AddTocliente(cliente cliente)
        {
            base.AddObject("cliente", cliente);
        }
    
        /// <summary>
        /// Método preterido para adicionar um novo objeto ao EntitySet imoveis. Em vez disso, experimente usar o método .Add da propriedade ObjectSet&lt;T&gt; associada.
        /// </summary>
        public void AddToimoveis(imoveis imoveis)
        {
            base.AddObject("imoveis", imoveis);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// Nenhuma Documentação de Metadados disponível.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="imobiliariaModel1", Name="cliente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class cliente : EntityObject
    {
        #region Método de Fábrica
    
        /// <summary>
        /// Crie um novo objeto cliente.
        /// </summary>
        /// <param name="id">Valor inicial da propriedade id.</param>
        /// <param name="nome_completo">Valor inicial da propriedade nome_completo.</param>
        /// <param name="cpf">Valor inicial da propriedade cpf.</param>
        /// <param name="tipo_de_pessoa">Valor inicial da propriedade tipo_de_pessoa.</param>
        /// <param name="status">Valor inicial da propriedade status.</param>
        /// <param name="login">Valor inicial da propriedade login.</param>
        /// <param name="senha">Valor inicial da propriedade senha.</param>
        public static cliente Createcliente(global::System.Int32 id, global::System.String nome_completo, global::System.String cpf, global::System.String tipo_de_pessoa, global::System.Boolean status, global::System.String login, global::System.String senha)
        {
            cliente cliente = new cliente();
            cliente.id = id;
            cliente.nome_completo = nome_completo;
            cliente.cpf = cpf;
            cliente.tipo_de_pessoa = tipo_de_pessoa;
            cliente.status = status;
            cliente.login = login;
            cliente.senha = senha;
            return cliente;
        }

        #endregion

        #region Propriedades Simples
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nome_completo
        {
            get
            {
                return _nome_completo;
            }
            set
            {
                Onnome_completoChanging(value);
                ReportPropertyChanging("nome_completo");
                _nome_completo = StructuralObject.SetValidValue(value, false, "nome_completo");
                ReportPropertyChanged("nome_completo");
                Onnome_completoChanged();
            }
        }
        private global::System.String _nome_completo;
        partial void Onnome_completoChanging(global::System.String value);
        partial void Onnome_completoChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cpf
        {
            get
            {
                return _cpf;
            }
            set
            {
                OncpfChanging(value);
                ReportPropertyChanging("cpf");
                _cpf = StructuralObject.SetValidValue(value, false, "cpf");
                ReportPropertyChanged("cpf");
                OncpfChanged();
            }
        }
        private global::System.String _cpf;
        partial void OncpfChanging(global::System.String value);
        partial void OncpfChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> data_nascimento
        {
            get
            {
                return _data_nascimento;
            }
            set
            {
                Ondata_nascimentoChanging(value);
                ReportPropertyChanging("data_nascimento");
                _data_nascimento = StructuralObject.SetValidValue(value, "data_nascimento");
                ReportPropertyChanged("data_nascimento");
                Ondata_nascimentoChanged();
            }
        }
        private Nullable<global::System.DateTime> _data_nascimento;
        partial void Ondata_nascimentoChanging(Nullable<global::System.DateTime> value);
        partial void Ondata_nascimentoChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sexo
        {
            get
            {
                return _sexo;
            }
            set
            {
                OnsexoChanging(value);
                ReportPropertyChanging("sexo");
                _sexo = StructuralObject.SetValidValue(value, true, "sexo");
                ReportPropertyChanged("sexo");
                OnsexoChanged();
            }
        }
        private global::System.String _sexo;
        partial void OnsexoChanging(global::System.String value);
        partial void OnsexoChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tipo_de_pessoa
        {
            get
            {
                return _tipo_de_pessoa;
            }
            set
            {
                Ontipo_de_pessoaChanging(value);
                ReportPropertyChanging("tipo_de_pessoa");
                _tipo_de_pessoa = StructuralObject.SetValidValue(value, false, "tipo_de_pessoa");
                ReportPropertyChanged("tipo_de_pessoa");
                Ontipo_de_pessoaChanged();
            }
        }
        private global::System.String _tipo_de_pessoa;
        partial void Ontipo_de_pessoaChanging(global::System.String value);
        partial void Ontipo_de_pessoaChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value, "status");
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.Boolean _status;
        partial void OnstatusChanging(global::System.Boolean value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String login
        {
            get
            {
                return _login;
            }
            set
            {
                OnloginChanging(value);
                ReportPropertyChanging("login");
                _login = StructuralObject.SetValidValue(value, false, "login");
                ReportPropertyChanged("login");
                OnloginChanged();
            }
        }
        private global::System.String _login;
        partial void OnloginChanging(global::System.String value);
        partial void OnloginChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String senha
        {
            get
            {
                return _senha;
            }
            set
            {
                OnsenhaChanging(value);
                ReportPropertyChanging("senha");
                _senha = StructuralObject.SetValidValue(value, false, "senha");
                ReportPropertyChanged("senha");
                OnsenhaChanged();
            }
        }
        private global::System.String _senha;
        partial void OnsenhaChanging(global::System.String value);
        partial void OnsenhaChanged();

        #endregion

        #region Propriedades de Navegação
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("imobiliariaModel1", "FK_cliente_imovel", "imoveis")]
        public EntityCollection<imoveis> imoveis
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<imoveis>("imobiliariaModel1.FK_cliente_imovel", "imoveis");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<imoveis>("imobiliariaModel1.FK_cliente_imovel", "imoveis", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Nenhuma Documentação de Metadados disponível.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="imobiliariaModel1", Name="imoveis")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class imoveis : EntityObject
    {
        #region Método de Fábrica
    
        /// <summary>
        /// Crie um novo objeto imoveis.
        /// </summary>
        /// <param name="rua">Valor inicial da propriedade rua.</param>
        /// <param name="bairro">Valor inicial da propriedade bairro.</param>
        /// <param name="numero">Valor inicial da propriedade numero.</param>
        /// <param name="id">Valor inicial da propriedade id.</param>
        /// <param name="cidade">Valor inicial da propriedade cidade.</param>
        /// <param name="cep">Valor inicial da propriedade cep.</param>
        /// <param name="fone">Valor inicial da propriedade fone.</param>
        public static imoveis Createimoveis(global::System.String rua, global::System.String bairro, global::System.Int32 numero, global::System.Int32 id, global::System.String cidade, global::System.String cep, global::System.String fone)
        {
            imoveis imoveis = new imoveis();
            imoveis.rua = rua;
            imoveis.bairro = bairro;
            imoveis.numero = numero;
            imoveis.id = id;
            imoveis.cidade = cidade;
            imoveis.cep = cep;
            imoveis.fone = fone;
            return imoveis;
        }

        #endregion

        #region Propriedades Simples
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String rua
        {
            get
            {
                return _rua;
            }
            set
            {
                OnruaChanging(value);
                ReportPropertyChanging("rua");
                _rua = StructuralObject.SetValidValue(value, false, "rua");
                ReportPropertyChanged("rua");
                OnruaChanged();
            }
        }
        private global::System.String _rua;
        partial void OnruaChanging(global::System.String value);
        partial void OnruaChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String bairro
        {
            get
            {
                return _bairro;
            }
            set
            {
                OnbairroChanging(value);
                ReportPropertyChanging("bairro");
                _bairro = StructuralObject.SetValidValue(value, false, "bairro");
                ReportPropertyChanged("bairro");
                OnbairroChanged();
            }
        }
        private global::System.String _bairro;
        partial void OnbairroChanging(global::System.String value);
        partial void OnbairroChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String imagem1
        {
            get
            {
                return _imagem1;
            }
            set
            {
                Onimagem1Changing(value);
                ReportPropertyChanging("imagem1");
                _imagem1 = StructuralObject.SetValidValue(value, true, "imagem1");
                ReportPropertyChanged("imagem1");
                Onimagem1Changed();
            }
        }
        private global::System.String _imagem1;
        partial void Onimagem1Changing(global::System.String value);
        partial void Onimagem1Changed();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String imagem2
        {
            get
            {
                return _imagem2;
            }
            set
            {
                Onimagem2Changing(value);
                ReportPropertyChanging("imagem2");
                _imagem2 = StructuralObject.SetValidValue(value, true, "imagem2");
                ReportPropertyChanged("imagem2");
                Onimagem2Changed();
            }
        }
        private global::System.String _imagem2;
        partial void Onimagem2Changing(global::System.String value);
        partial void Onimagem2Changed();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String imagem3
        {
            get
            {
                return _imagem3;
            }
            set
            {
                Onimagem3Changing(value);
                ReportPropertyChanging("imagem3");
                _imagem3 = StructuralObject.SetValidValue(value, true, "imagem3");
                ReportPropertyChanged("imagem3");
                Onimagem3Changed();
            }
        }
        private global::System.String _imagem3;
        partial void Onimagem3Changing(global::System.String value);
        partial void Onimagem3Changed();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 numero
        {
            get
            {
                return _numero;
            }
            set
            {
                OnnumeroChanging(value);
                ReportPropertyChanging("numero");
                _numero = StructuralObject.SetValidValue(value, "numero");
                ReportPropertyChanged("numero");
                OnnumeroChanged();
            }
        }
        private global::System.Int32 _numero;
        partial void OnnumeroChanging(global::System.Int32 value);
        partial void OnnumeroChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> valor_aluguel
        {
            get
            {
                return _valor_aluguel;
            }
            set
            {
                Onvalor_aluguelChanging(value);
                ReportPropertyChanging("valor_aluguel");
                _valor_aluguel = StructuralObject.SetValidValue(value, "valor_aluguel");
                ReportPropertyChanged("valor_aluguel");
                Onvalor_aluguelChanged();
            }
        }
        private Nullable<global::System.Double> _valor_aluguel;
        partial void Onvalor_aluguelChanging(Nullable<global::System.Double> value);
        partial void Onvalor_aluguelChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> valor_de_venda
        {
            get
            {
                return _valor_de_venda;
            }
            set
            {
                Onvalor_de_vendaChanging(value);
                ReportPropertyChanging("valor_de_venda");
                _valor_de_venda = StructuralObject.SetValidValue(value, "valor_de_venda");
                ReportPropertyChanged("valor_de_venda");
                Onvalor_de_vendaChanged();
            }
        }
        private Nullable<global::System.Double> _valor_de_venda;
        partial void Onvalor_de_vendaChanging(Nullable<global::System.Double> value);
        partial void Onvalor_de_vendaChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> id_cliente
        {
            get
            {
                return _id_cliente;
            }
            set
            {
                Onid_clienteChanging(value);
                ReportPropertyChanging("id_cliente");
                _id_cliente = StructuralObject.SetValidValue(value, "id_cliente");
                ReportPropertyChanged("id_cliente");
                Onid_clienteChanged();
            }
        }
        private Nullable<global::System.Int32> _id_cliente;
        partial void Onid_clienteChanging(Nullable<global::System.Int32> value);
        partial void Onid_clienteChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cidade
        {
            get
            {
                return _cidade;
            }
            set
            {
                OncidadeChanging(value);
                ReportPropertyChanging("cidade");
                _cidade = StructuralObject.SetValidValue(value, false, "cidade");
                ReportPropertyChanged("cidade");
                OncidadeChanged();
            }
        }
        private global::System.String _cidade;
        partial void OncidadeChanging(global::System.String value);
        partial void OncidadeChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cep
        {
            get
            {
                return _cep;
            }
            set
            {
                OncepChanging(value);
                ReportPropertyChanging("cep");
                _cep = StructuralObject.SetValidValue(value, false, "cep");
                ReportPropertyChanged("cep");
                OncepChanged();
            }
        }
        private global::System.String _cep;
        partial void OncepChanging(global::System.String value);
        partial void OncepChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descricao_imovel
        {
            get
            {
                return _descricao_imovel;
            }
            set
            {
                Ondescricao_imovelChanging(value);
                ReportPropertyChanging("descricao_imovel");
                _descricao_imovel = StructuralObject.SetValidValue(value, true, "descricao_imovel");
                ReportPropertyChanged("descricao_imovel");
                Ondescricao_imovelChanged();
            }
        }
        private global::System.String _descricao_imovel;
        partial void Ondescricao_imovelChanging(global::System.String value);
        partial void Ondescricao_imovelChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String fone
        {
            get
            {
                return _fone;
            }
            set
            {
                OnfoneChanging(value);
                ReportPropertyChanging("fone");
                _fone = StructuralObject.SetValidValue(value, false, "fone");
                ReportPropertyChanged("fone");
                OnfoneChanged();
            }
        }
        private global::System.String _fone;
        partial void OnfoneChanging(global::System.String value);
        partial void OnfoneChanged();

        #endregion

        #region Propriedades de Navegação
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("imobiliariaModel1", "FK_cliente_imovel", "cliente")]
        public cliente cliente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cliente>("imobiliariaModel1.FK_cliente_imovel", "cliente").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cliente>("imobiliariaModel1.FK_cliente_imovel", "cliente").Value = value;
            }
        }
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<cliente> clienteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cliente>("imobiliariaModel1.FK_cliente_imovel", "cliente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<cliente>("imobiliariaModel1.FK_cliente_imovel", "cliente", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
