//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace imobiliaria
{
    using System;
    using System.Collections.Generic;
    
    public partial class imoveis
    {
        public string rua { get; set; }
        public string bairro { get; set; }
        public string imagem1 { get; set; }
        public string imagem2 { get; set; }
        public string imagem3 { get; set; }
        public int numero { get; set; }
        public Nullable<double> valor_aluguel { get; set; }
        public Nullable<double> valor_de_venda { get; set; }
        public int id { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public string cidade { get; set; }
        public string cep { get; set; }
        public string descricao_imovel { get; set; }
        public string fone { get; set; }
    
        public virtual cliente cliente { get; set; }
    }
}
